dist: trusty
sudo: false

language: node_js
node_js:
   - node # will use latest node

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache: yarn

script: # the build step
   - yarn run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
   - yarn run deploy

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

deploy:
  local-dir: docs
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
